# Default settings
#
# Syntax can be learned from Dynaconf examples 
# https://github.com/rochacbruno/learndynaconf/tree/main/configs

[alert]
campana_url = "http://httpbin.org/post"
platform = 'localhost'

[logging.loggers.nextline_alert]
handlers = ["default"]
level = "DEBUG"
